import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { Product } from '../types'
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import ProductCard from '../components/ProductCard'
import NoResults from '../components/NoResults'

interface IProps {
  products: Product[]
}

const inter = Inter({
  variable: '--inter-font', display: 'swap', subsets: ['latin'],
})

 const Home = ( { products }: IProps ) => {
  return (
    <>
      <Head>
        <title>Everything Cedar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='xl:w-[1200px]  overflow-hidden h-[100vh]'>
        <Header />
        <div className='flex gap-6 md:gap-2 '>
          <div className='h-[92vh] overflow-hidden xl:hover:overflow-auto'>
            <Sidebar />
          </div>
          <div className='mt-4 flex flex-col gap-6 overflow-auto h-[88vh] videos flex-1'>
      <main className={styles.main}>
        <div className={inter.variable}>
        <div className='grid grid-cols-2 md:grid-cols-3 w-full gap-4 lg:gap-1 pr-4 videos h-full'>
        {products.length ? (
          products.map((product: Product) => (
            <ProductCard list={product} key={product._id} />
          ))
        ) : (
          <NoResults text={'NO New Products... Check Back Later'} />
        )
        }
      </div>
      </div>
      </main>
      </div>
        </div>
      </div>
    </>
  )
}


export const getServerSideProps = async () => {
  const { data } = await axios.get(`http://localhost:3000/api/products`);

  

  return {
    props: {
      products: data
    },
  }
}

export default Home